version: 0.0
Resources:
  - TargetService:
      Type: AWS::ECS::Service
      Properties:
        TaskDefinition: "arn:aws:ecs:ap-south-1:077286633283:task-definition/rule:4"
        LoadBalancerInfo:
          ContainerName: "nginx"
          ContainerPort: 3000
